key_vault_url: "<vault-url>"
openai:
  endpoint: "<openai-endpoint>"
  deployment: "<model-deployment-name>"
  api_version: "2024-03-01-preview"
cosmos:
  url: "<cosmos-url>"
  database: "<db-name>"
  key_secret_name: "COSMOS-PRIMARY-KEY"
