name: Deploy Backend to Azure App Service
  uses: azure/webapps-deploy@v2
  with:
    app-name: aiagentsgov-backend 
    publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
    package: ./src/backend
  
on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: aiagentsgov-backend
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
        package: ./src/backend
