name: Deploy Backend to Azure Container App

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINER_APP_NAME: camar01
      AZURE_RESOURCE_GROUP: SomcAI-Project-RG
      AZURE_REGION: swedencentral
      DOCKERFILE_PATH: src/backend/Dockerfile.azure
      REGISTRY_LOGIN_SERVER: somcregistrysweden.azurecr.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        uses: azure/container-apps-deploy-action@v1
        with:
          appName: ${{ env.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          imageToBuild: ${{ env.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}
          dockerfilePath: ${{ env.DOCKERFILE_PATH }}
          registryUrl: ${{ env.REGISTRY_LOGIN_SERVER }}
          location: ${{ env.AZURE_REGION }}
