name: Trigger auto deployment for frontend-aiagents-gov

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/frontend-aiagents-gov-AutoDeployTrigger-76f2e975-374e-4a4e-8b9a-db88de619453.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FRONTENDAIAGENTSGOV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRONTENDAIAGENTSGOV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRONTENDAIAGENTSGOV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ca2a76f03945acr.azurecr.io
          registryUsername: ${{ secrets.FRONTENDAIAGENTSGOV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONTENDAIAGENTSGOV_REGISTRY_PASSWORD }}
          containerAppName: frontend-aiagents-gov
          resourceGroup: rg-info-2259
          imageToBuild: ca2a76f03945acr.azurecr.io/frontend-aiagents-gov:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


