name: Trigger auto deployment for krowemafrai-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/krowemafrai-app-AutoDeployTrigger-17c1e52b-7bee-4293-b24f-2ceebea859e3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KROWEMAFRAIAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KROWEMAFRAIAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KROWEMAFRAIAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: krowemafraiacr.azurecr.io
          registryUsername: ${{ secrets.KROWEMAFRAIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KROWEMAFRAIAPP_REGISTRY_PASSWORD }}
          containerAppName: krowemafrai-app
          resourceGroup: krowemafrai-rg
          imageToBuild: krowemafraiacr.azurecr.io/krowemafrai-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


