name: Build and deploy Python app to Azure Web App - aiagentsgov-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install zip
        run: sudo apt-get install zip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip only app files (flat structure)
        run: |
          mkdir upload
          cp -r *.py requirements.txt azure.yaml upload/
          zip -r release.zip upload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A554F8148EC544B7A5FC4388C541F484 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A99394C1F8F440D9772F371113CBA48 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_989248AB5335474EABE443589D0AA894 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aiagentsgov-backend'
          slot-name: 'Production'
          package: release.zip
