  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install zip
        run: sudo apt-get install zip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Maak startup.txt met startup command voor Azure
        run: echo "gunicorn -w 1 -k uvicorn.workers.UvicornWorker app_kernel:app" > startup.txt

      - name: Zip artifact for deployment (incl. azure.yaml + startup.txt)
        run: zip -r release.zip . -x "venv/*" ".git/*" "*.zip"
