name: Build and deploy Python app to Azure - BackendAIGovNieuw

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test if application starts
        run: |
          source venv/bin/activate
          python -c "from main import app; print('App imported successfully')"
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Create startup script for Azure
        run: |
          echo "#!/bin/bash" > startup.sh
          echo "cd /home/site/wwwroot" >> startup.sh
          echo "export PORT=\${PORT:-8000}" >> startup.sh
          echo "python -m uvicorn main:app --host 0.0.0.0 --port \$PORT" >> startup.sh
          chmod +x startup.sh

      - name: Create runtime.txt for Python version detection
        run: echo "python-3.13" > runtime.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "venv/*" ".git/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B56FB896AFD48948EF365DD7978088C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69FF20C66F594B6EAD0F70801F9CBECF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B36ED8D8811C4986991751EC07FFFA4D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'BackendAIGovNieuw'
          slot-name: 'Production'
          
